### ISSUE TITLE
AggregPMean not compatible with GPU optimization

### ISSUE THREAD

**Issue by liamorra** [logictensornetworks/LTNtorch#1]
In the torch package, the AggregPMean throws an error "'mask' must be a torch.BoolTensor." when trained with GPU optimization. According to my tests, the issue is the instruction:

` if not isinstance(mask, torch.BoolTensor):
                raise ValueError("'mask' must be a torch.BoolTensor.")
`
which should be 

` if not isinstance(mask, torch.BoolTensor) or not isinstance(mask, torch.cuda.BoolTensor):
                raise ValueError("'mask' must be a torch.BoolTensor or torch.cuda.BoolTensor.")
`
since the correct type would be torch.cuda.BoolTensor when GPU optimization is enabled. 

I am not  a Pytorch expert, so there might a more elegant solution.

**Comment by tommasocarraro** [comment]
Hi @liamorra,
Thank you very much for your feedback and for using this project for your work.

From the error that you wrote here, it seems that the problem is not something related to the aggregator (AggregPMean). 

Instead, it seems it is related to the fact that you used "guarded quantification" in the implementation of your work. To be more clear, guarded quantification is a special type of quantification that quantifies only the truth values whose groundings satisfy a certain condition. For example, Forall x > 5, P(x). This is implemented internally with a boolean mask that put at zero all the truth values whose groundings do not satisfy the condition.

Since I do not have access to your project, could you kindly try to change that part at your local library and come back to me? I would like to know if your solution worked. In that case, I will change that in the library. You can easily do that with Pycharm. You can access the code that raised the exception and try to change the binaries. 

Thank you very much for your precious feedback.

**Comment by liamorra** [comment]
Hi @tommasocarraro, 

Sorry for the late reply in getting back to you. 

Yes, you are right and it is an issue that is faced when using guarded quantification. 

The error can be easily reproduced using the notebook 4-semi-supervised_pattern_recognition.ipynb provided with the library con Colab. Here are the steps that I followed:

1. Open the notebook in Colab
2. Change the runtime to GPU
3. Add the instruction` !pip install LTNtorch` at the beginning of the notebook
4. Run the notebook.

The error that you get is the following:

[/usr/local/lib/python3.8/dist-packages/ltn/fuzzy_ops.py](https://localhost:8080/#) in __call__(self, xs, dim, keepdim, mask, p, stable)
   1373                 raise ValueError("'xs' and 'mask' must have the same shape.")
   1374             if not isinstance(mask, torch.BoolTensor):
-> 1375                 raise ValueError("'mask' must be a torch.BoolTensor.")
   1376             # we sum the values of xs which are not filtered out by the mask
   1377             numerator = torch.sum(torch.where(~mask, torch.zeros_like(xs), xs), dim=dim, keepdim=keepdim)

**ValueError: 'mask' must be a torch.BoolTensor.**

If you redefine the AggrePMean operator, and substitute:
```
           if not isinstance(mask, torch.BoolTensor): raise ValueError("'mask' must be a torch.BoolTensor.")
```
with
```
            if not (isinstance(mask, torch.cuda.BoolTensor) or isinstance(mask, torch.BoolTensor)):
                raise ValueError("'mask' must be a torch.BoolTensor or torch.cuda.BoolTensor.")
```
the notebook works as expected. In Pytorch, datatypes may differ from CPU to GPU:
https://pytorch.org/docs/stable/tensors.html

**Comment by tommasocarraro** [comment]
Dear @liamorra,
Thank you very much for your feedback and help.

The new release of LTNtorch has been just released and solves this issue.
